language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
  - SECRET=1234567890
  - NODE_ENV=development
  - DATABASE_URL=postgres://wfaxdwyk:ll8eVrua7F8R0-LQvgwCD2mcqFkCqFwe@isilo.db.elephantsql.com:5432/wfaxdwyk

after_success: npm run coverage

